### ISSUE TITLE
__STACKTRACE__

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#190]
Support both the older BIF and the optimized instrinic

- [x] [`get_stacktrace/0`](http://erlang.org/doc/man/erlang.html#get_stacktrace-0) (https://github.com/lumen/lumen/pull/360)
- [x] `__STACKTRACE__` . In Erlang this is a change to the `catch` syntax so part of the compiler

**Comment by bcardarella** [comment]
Has been implemented
