### ISSUE TITLE
Implement general Erlang term printer

### ISSUE THREAD

**Issue by bitwalker** [lumen/lumen#193]
In order to provide output functions which pretty print values of type `Term`, we need a pretty printer. Internally in Rust, we have `Debug` (and sometimes `Display`) implementations for the various term types, but we should probably have a trait especially for Erlang term printing, something like `PrettyPrint` or `DisplayErlang`, etc. In addition to the trait, we'll need a `Formatter` implementation that provides helpers to make writing implementations of `PrettyPrint` (or whatever) relatively simple and straight forward.

**Comment by bcardarella** [comment]
Has been implemented
