### ISSUE TITLE
Source Chain demo example instructions don't work (are possibly incomplete)

### ISSUE THREAD

**Issue by shaheenery** [lumen/lumen#276]
Having watched Luke, Brian, and Paul's demo from Elixirconf, I wanted to start playing around with what was working.  I didn't follow the instructions for setting up the dev env for lumen since I know nothing of wasm and little of rust and I jumped to the example readme.

I encountered multiple issues trying to get the demo working by following instructions.  I thought I would be helpful for the community to help flesh this out. (at least for os x)

**Comment by KronicDeth** [comment]
@shaheenery it would be more helpful if you actually listed your errors.   We can't triage or reproduce your issues if we don't no the specifics of what you hit.

**Comment by KronicDeth** [comment]
Fixed by #279.
