### ISSUE TITLE
badarg! should include stacktrace

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#359]
Based on the examples in the docs for [`get_stacktrace/0`](http://erlang.org/doc/man/erlang.html#get_stacktrace-0), `:badarg` exception should have a stacktrace when caught with `catch` or when using `get_stacktrace`.  However, the `badarg` macro and other exception macros do not do this, so most of the usages are not going to show helpful stacktraces.

- [ ] Generate stacktraces for all exception macros from the `Process::stacktrace()`.

**Comment by bitwalker** [comment]
This and #363 should probably depend on #366 being implemented. #363 in particular will benefit from waiting, since the actual change there is really small without all the refactoring to get `Process` references passed around.

**Comment by bcardarella** [comment]
No longer required
