### ISSUE TITLE
Trouble building the project for the first time

### ISSUE THREAD

**Issue by marcdel** [lumen/lumen#371]
Hi all 👋🏼,

I'm trying to build this project for the first time and running into a few issues. Super new to rust and haven't done any c since college so there may be obvious things I'm missing. If this is actually an llvm issue, I'm happy to take the conversation over there, I just don't know enough to tell.

```
macOS Catalina 10.15.2
rustc 1.41.0-nightly (c8ea4ace9 2019-12-14)
cargo 1.41.0-nightly (626f0f40e 2019-12-03)
```
(lemme know if there's other info that'd be useful for debugging and I can include it)

The directions in the readme worked great for me up until the LLVM step.

I brew installed `ninja`, `ccache`, and `cmake`. There doesn't seem to be a keg for clang, but I've got a version shipped with the OS. No idea if this is a useful version or not though: `Apple clang version 11.0.0 (clang-1100.0.33.12)`.

The first thing I ran into was that llvm-project doesn't have a Makefile, so `make llvm` doesn't work, but the llvm-project docs have build steps so I followed those and did `mcd build && cmake -G Ninja ../llvm` and then `ninja`. This seemed to do vaguely useful things and exit successfully? Are there other options I need to build it with?

So next I restarted iTerm (just in case!), and moved into the lumen folder and ran `make build`. This fails loading the `hasbrown` dependency with the following output:

```
➜  lumen git:(develop) make build
LLVM_SYS_90_PREFIX=`cd ~/.local/share/llvm/lumen && pwd` cargo build
/bin/sh: line 0: cd: /Users/marc/.local/share/llvm/lumen: No such file or directory
    Updating git repository `https://github.com/hansihe/hashbrown`
error: failed to load source for a dependency on `hashbrown`

Caused by:
  Unable to update https://github.com/hansihe/hashbrown#fc6e2652

Caused by:
  revspec 'fc6e265214edf3731944a9ae5e879990c743ccfe' not found; class=Reference (4); code=NotFound (-3)
make: *** [build] Error 101
```

It seems like the actual error is that lumen expects llvm things to be in `~/.local/share/llvm` and that apparently didn't happen.

I also tried passing that local/share directory to cmake and got:

```
➜  build git:(master) cmake -G Ninja ~/.local/share/llvm
CMake Error: The source directory "/Users/marc/.local/share/llvm" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

I tried moving `llvm-project` to `~/.local/share/llvm` which I didn't really expect to work, but I'm kind of out of ideas. There's still no lumen folder there, so it fails in the same way.

Any help would be appreciated! Happy to update the readme as well if this isn't just a me problem.

Thanks!

**Comment by KronicDeth** [comment]
Don’t worry about building LLVM.  It is needed for building the compiler part and it is still being built.  You can use nightly cargo to cargo build the workspace and you’ll be fine for now.

**Comment by marcdel** [comment]
Hmm, doing `cargo build` directly still gives me the second error. Verified with a fresh install on a second machine.

```
➜  lumen git:(develop) cargo build
    Updating crates.io index
    Updating git repository `https://github.com/KronicDeth/parking_lot.git`
    Updating git repository `https://github.com/japaric/heapless`
    Updating git repository `https://github.com/eirproject/eir.git`
    Updating git repository `https://github.com/hansihe/num-bigint.git`
    Updating git repository `https://github.com/hansihe/hashbrown`
error: failed to load source for a dependency on `hashbrown`

Caused by:
  Unable to update https://github.com/hansihe/hashbrown#fc6e2652

Caused by:
  revspec 'fc6e265214edf3731944a9ae5e879990c743ccfe' not found; class=Reference (4); code=NotFound (-3)
```

That sha definitely exists:

```
➜  lumen git:(develop) curl -I https://github.com/hansihe/hashbrown\#fc6e2652
HTTP/1.1 200 OK
Date: Sun, 15 Dec 2019 20:15:44 GMT
Content-Type: text/html; charset=utf-8
Server: GitHub.com
Status: 200 OK
```

But the version specified in the lock file (0.5.0) looks like it has a different sha (e7cd4a5)? https://github.com/rust-lang/hashbrown/releases/tag/v0.5.0

Maybe the lock file has gotten into an invalid state somehow?

**Comment by KronicDeth** [comment]
@marcdel I'm seeing the same problem on CI builds (https://github.com/lumen/lumen/pull/370/checks?check_run_id=353670840).  @hansihe did you change something with your fork that broke the rev?

**Comment by marcdel** [comment]
Just pulled and it builds successfully for me. Thanks! 💜
