### ISSUE TITLE
Any call to `exit` results in failed assertion in the codegen

### ISSUE THREAD

**Issue by hansihe** [lumen/lumen#559]
With https://github.com/lumen/lumen/pull/551 (simply updates eir, some changes to the IR produced by passes), any module which calls `exit` results in a failed assertion in the compiler.

```
-module(init).
-export([start/0]).

start() ->
    exit(abnormal).
```

```
lumen: /lumen/compiler/codegen_llvm/lib/lumen/EIR/Builder/ModuleBuilder.cpp:1153: bool lumen::eir::ModuleBuilder::maybe_build_intrinsic(mlir::Location, llvm::StringRef, ArrayRef<mlir::Value>, bool, mlir::Block *, ArrayRef<mlir::Value>): Assertion `resultOpt.hasValue()' failed.
```

The eir seems to be valid to me, it's very simple:
```
start/0 {
  block22(%57, %58):
    %28 = a'erlang':a'exit'/1;
    %28(a'abnormal') => %57 except %58;
}
```

**Comment by KronicDeth** [comment]
@hansihe are you using latest `develop` after https://github.com/lumen/lumen/commit/c94715cffedf16ea353cf074f9d427bb0d023540?  My #549 included a change to use OTP's `erlang:exit/0` that fixed a problem with using the `__lumen_builtin_exit` for Erlang-code level exits, but I only merged it 9 hours ago.  I use `exit/1` in my tests for various spawns, so I know it works, but I don't `exit(abnormal)` in `start/0` itself, so this could be different.

**Comment by hansihe** [comment]
Yep, I am using latest after your merge, that could explain things.
