### ISSUE TITLE
zsh: exec format error: /opt/lumen/bin/lumen

### ISSUE THREAD

**Issue by conradwt** [lumen/lumen#573]
I have installed **lumen** using the instructions from the release notes but getting the following message on macOS 10.15.6:

```zsh
/opt/lumen/bin/lumen help
zsh: exec format error: /opt/lumen/bin/lumen
```

**Comment by KronicDeth** [comment]
This works for me on 10.15.6, so I'm not sure what the difference could me.  Are you sure you grabbed the macOS tarball and not the Linux one?

**Comment by conradwt** [comment]
@KronicDeth Yes, I have downloaded the Linux instead of the macOS tarball.  Thus, the above works as expected and I'm closing this issue.
