### ISSUE TITLE
I/O errors should include the path that the error occurred on

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#579]
When trying to compile `init.erl` from `erlang/otp`, the parsing error isn't obvious what is wrong:

```
lumen compile --output-dir _build erts/preloaded/src/init.erl 
   Compiling erts/preloaded/src/init.erl
error: No such file or directory (os error 2)

error: parsing failed

      Failed erts/preloaded/src/init.erl
```

Which file or directory doesn't exist?  The output directory, `_build` exists as does `erts/preloaded/src/init.erl `.

We should include file names/paths for when this happens.  @hansihe I think this is happening in the EIR libraries that `lumen` is calling, so may need to transfer this issue to it.

**Comment by bitwalker** [comment]
@KronicDeth is this fixed with the recent fixes @hansihe applied to the parser?

**Comment by bcardarella** [comment]
Majority has been fixed but not 100% yet. Closing in favor of future work.
