### ISSUE TITLE
Implement binary matching/construction

### ISSUE THREAD

**Issue by bitwalker** [lumen/lumen#6]
Erlang's bit/binary syntax for matching and construction relies on a combination of runtime support and associated BEAM instructions. Like OTP, our implementation will also rely on runtime support, but will instead compile such expressions directly to invocations of those runtime functions.

The design of binary matching/construction is based on the following pieces:

## Data Representation

A binary consists of the following structure:

- A data block (header, size, binary data)
- A header block (header, pointer to data block, offset O, size S, bit offset BO, and bit size BS)

The above represents a binary of size (S * 8 + BS) and offset at (O * 8 + BO), in the data block. BS and BO both have values in the range of 0-7. To be clear, both O and BO, and S and BS are needed to calculate sizes/offsets.

The following runtime support functions are needed:

- `binary_start_match` calculates metadata needed before matching begins
- `binary_skip_bits` used during matching when the segment to match involves a variable
- `binary_get_<type>` used during matching to read a number of bits and construct a term of type `<type>` from them, e.g. `binary_get_integer`
- `binary_put_<type>` like `binary_get_<type>`, but constructs a number of bits from a term of type `<type>`, e.g. `binary_put_integer`
- `binary_put_any`, dynamically determines the runtime type of its value and performs the actions of `binary_put_<type>`
- `binary_init` allocates memory for the data block, returns the pointer and an initial offset of 0
- `binary_final` creates binary header from the data block pointer and final offset, giving the total size of the binary

### Matching

The following pseudocode represents how the above pieces are used to perform matching:

```erlang
{Offset0, BinSize, Ptr} = binary_start_match(Bin),
EffSize1 = Size1 * Unit1,
%% Specifiers determines how binary data is transformed to term of type <type>
{X1, Offset1} = binary_get_Type1(Specifiers1, EffSize1, Offset0, BinSize, Ptr),
Value1 = X1,
%% EffSizeN = SizeN * UnitN,
%% ...
case OffsetN - 1 of
  BinSize -> Success;
  _Other -> Failure
end
```

### Construction

The following pseudocode represents how the above pieces are used to perform binary construction:

```erlang
ValueN = ExprN,
EffSizeN = SizeN * UnitN,
BinSize = lists:sum([EffSize1, .., EffSizeN]),
{Offset0, Ptr} = binary_init(BinSize),
OffsetN = binary_put_TypeN(SpecifiersN, EffSizeN, ValueN, OffsetN-1, Ptr),
NewBin = binary_final(OffsetN, Base)
```

### Comprehensions

The Construction section also illustrates the pattern for compiling bit comprehensions with known sizes (i.e. the maximum effective size is determined statically, then allocated all at once, after which each segment is written to it). In the case of non-constant size expressions, it is necessary to fall back to a less efficient algorithm which builds each segment, and then at the very end, copies them all to a new memory area which will hold the finished binary. In LLVM we can do this more efficiently, but ideally we will find ways to always determine the size statically, so we can take the more efficient route.

### Implementation

My feeling is that the runtime support for this should probably be implemented directly in LLVM IR, rather than implementing in Rust and using FFI calls. The reason being that I think we will benefit from additional optimizations that LLVM can provide, as well as avoid the extra boilerplate needed when crossing the FFI barrier. This does mean writing LLVM IR by hand, but for this specific algorithm, I think it is actually very straightforward, as the IR has all the functions we need to do bitmasking and the like. The primary thing we will likely still need runtime support for is determining the size of things we are trying to encode to binary, but we may be able to get that in LLVM as well, I haven't gotten to that point yet in the compiler.

**Comment by bcardarella** [comment]
Have been implemented
