### ISSUE TITLE
Expected constant to be an atom

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#628]
```
thread '<unnamed>' panicked at 'expected constant const_valueNN to be an atom', compiler/codegen/src/builder/function.rs:458:13
```

Affects the following files in OTP

* `erts/preloaded/src/atomics.erl`
* `lib/et/src/et.erl`
* `lib/inets/src/http_server/httpd_acceptor.erl`
* `lib/tftp/src/tftp_engine.erl`

**Comment by bitwalker** [comment]
Closing this as wontfix since the compiler was rewritten since this issue was opened, if a similar issue is still present we should create a new bug to track it
