### ISSUE TITLE
Named return in an union not supported

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#629]
Can't use `::` to separate a name in a return, but in a union, so different than #464.

Affects the following files in OTP

* `erts/preloaded/src/erlang.erl`
* `lib/wx/src/wx_object.erl`

**Comment by hansihe** [comment]
Fixed by https://github.com/eirproject/eir/commit/8bcf7a788f301befbb8ccac52118feba80b5fb85

**Comment by KronicDeth** [comment]
Confirmed.  `erlang.erl` and `wx_object.erl` no longer show this error.
