### ISSUE TITLE
Named fun not parsable

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#632]
Although we refer to `fun`s as anonymous functions, Erlang (unlike Elixir) actually supports named `fun`s since Erlang 17 to support self-recursion, such as

```erlang
fun F({A,_,_},{B,_,_}) ->
                       F(A,B);
                   F(A,B) ->
                       A =< B
               end
```

Affects the following files in OTP:

* `lib/kernel/src/code.erl`
* `lib/kernel/src/logger_simple_h.erl`
* `lib/runtime_tools/src/msacc.erl`

**Comment by hansihe** [comment]
This should be fixed by https://github.com/eirproject/eir/commit/ef2c1c968aef80f3ccdf375972bc056f66730306

**Comment by KronicDeth** [comment]
Confirmed.  `code.erl`, `logger_simple_h.erl` and `msacc.erl` no longer show this error.
