### ISSUE TITLE
-compile(inline) is not supported

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#635]
I don't think we necessarily need to do the inlining it wants, we just need for EIR to parse it and maybe keep track that the flag is on to use later, but I kinda feel that Erlang-level inlining decisions have different performance and code size trade offs than native compiling with `lumen`, so it is probably best to ignore it for now.

```
warning: invalid compile option
    ┌─ /Users/runner/work/lumen/otp/lib/kernel/src/user.erl:21:10
    │
 21 │ -compile(inline).
    │          ^^^^^^ this option is either unsupported or unrecognized
```

Affects the following files in OTP:

* `lib/kernel/src/user.erl`
* `lib/wx/src/gen/glu.erl`
* `lib/wx/src/gen/gl.erl`

**Comment by hansihe** [comment]
Fixed by https://github.com/eirproject/eir/commit/2a89b9c03df60176e3fa9c0966abe287a4422195
