### ISSUE TITLE
CMake >= 3.20 not supported

### ISSUE THREAD

**Issue by coproduto** [lumen/lumen#690]
When trying to build Lumen, I would keep getting an error about CMake not understanding the `--build` argument while trying to build `lumen_tblgen`.

This was solved by downgrading CMake from 3.20.0 to 3.19.7.

I'm not sure if this is a real issue or something weird about my machine, but if other people can reproduce this, it might be a good idea to add a warning that CMake versions >= 3.20 will fail to compile `lumen_tblgen`.

**Comment by bitwalker** [comment]
Turns out this was CMake getting stricter about a few things, namely how it was parsing flags, and it no longer implicitly generates the build system, but it was a simple fix to get it working again. I'm running 3.20 now, so if anything else comes up, I imagine I'll catch it.
